# Generated by Django 5.2 on 2025-04-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('GBP', '£'), ('EUR', '€'), ('USD', '$')], default='GBP'),
            preserve_default=False,
        ),
    ]
