# Generated by Django 5.2 on 2025-04-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_remove_transaction_from_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionrequest',
            old_name='to_account',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='transactionrequest',
            old_name='from_account',
            new_name='sender',
        ),
    ]
